"""Independent raw-data reconstruction primitives for the frozen e2a rule.

The handover artifacts were generated by an exploratory one-second grid.  This
module names that behavior ``LEGACY_LAB_GRID_V1`` instead of treating it as the
governed execution definition.  Calendar and signal reconstruction always use
the frozen dataset lineage and physical raw trades; comparison against the lab
files is therefore able to expose, rather than inherit, their defects.
"""

from __future__ import annotations

import hashlib
import json
import os
import stat
from collections import OrderedDict
from collections.abc import Callable, Iterator
from contextlib import contextmanager
from dataclasses import dataclass
from datetime import UTC, date, datetime, timedelta
from itertools import pairwise
from pathlib import Path
from typing import BinaryIO, Final, Literal
from zoneinfo import ZoneInfo

import numpy as np
import pyarrow as pa
import pyarrow.compute as pc
import pyarrow.parquet as pq

from systematic_fx.research.bar_pipeline import load_bar_dataset_manifest

from .config import DATASET_MANIFEST_RELATIVE_PATH, DATASET_MANIFEST_SHA256, E2AConfig

DAY_SECONDS: Final = 86_400
SECOND_NS: Final = 1_000_000_000
TICK_PRICE_RAW: Final = 50_000
UNDEFINED_PRICE: Final = 9_223_372_036_854_775_807
F_MAYBE_BAD_BOOK: Final = 4
F_BAD_TS_RECV: Final = 8
F_SNAPSHOT: Final = 32
LEGACY_BAD_FLAG_MASK: Final = F_MAYBE_BAD_BOOK | F_BAD_TS_RECV | F_SNAPSHOT
LONDON: Final = ZoneInfo("Europe/London")

CalendarMode = Literal["CALENDAR_LAST_ELIGIBLE_WEEKDAY", "LEGACY_METAS_ADJACENCY"]


class E2AReproductionError(RuntimeError):
    """Frozen source data or a replay invariant failed closed."""


@dataclass(frozen=True, slots=True)
class DayPlan:
    source_date: date
    contract: str
    instrument_id: int
    source_sha256: str
    source_path: Path

    @property
    def midnight_epoch(self) -> int:
        return int(datetime.combine(self.source_date, datetime.min.time(), tzinfo=UTC).timestamp())


@dataclass(frozen=True, slots=True)
class TradeTape:
    physical_ts_ns: np.ndarray
    physical_price_ticks: np.ndarray
    bar_start_seconds: np.ndarray
    bar_close_ticks: np.ndarray

    def __post_init__(self) -> None:
        if len(self.physical_ts_ns) != len(self.physical_price_ticks):
            raise E2AReproductionError("trade tape physical columns differ in length")
        if len(self.bar_start_seconds) != len(self.bar_close_ticks):
            raise E2AReproductionError("trade tape bar columns differ in length")
        if len(self.physical_ts_ns) and np.any(np.diff(self.physical_ts_ns) < 0):
            raise E2AReproductionError("selected trade timestamps regressed")
        if len(self.bar_start_seconds) and np.any(np.diff(self.bar_start_seconds) <= 0):
            raise E2AReproductionError("one-second trade bars are not strictly ordered")

    def legacy_bar_close(self, epoch_second: int, *, maximum_staleness: int) -> int | None:
        """Exploratory-lab lookup: last whole-second bar whose *start* is <= t."""

        position = int(np.searchsorted(self.bar_start_seconds, epoch_second, side="right")) - 1
        if position < 0:
            return None
        bar_second = int(self.bar_start_seconds[position])
        if epoch_second - bar_second > maximum_staleness:
            return None
        return int(self.bar_close_ticks[position])

    def physical_trade_at_or_before(
        self,
        epoch_ns: int,
        *,
        maximum_staleness_seconds: int,
    ) -> int | None:
        """Last physical selected trade with ``ts_recv <= epoch_ns``."""

        position = int(np.searchsorted(self.physical_ts_ns, epoch_ns, side="right")) - 1
        if position < 0:
            return None
        age = epoch_ns - int(self.physical_ts_ns[position])
        if age < 0 or age > maximum_staleness_seconds * SECOND_NS:
            return None
        return int(self.physical_price_ticks[position])


@dataclass(frozen=True, slots=True)
class Quote:
    epoch_second: int
    bid_ticks: int
    ask_ticks: int
    source_state_ts_ns: int


@dataclass(frozen=True, slots=True)
class LegacyQuoteTape:
    """State changes used by the out-of-band lab's one-second replay.

    The lab treated the final selected row in an integer second as observable at
    that second and then carried it without an effective age limit.  Keeping
    this as an explicitly named compatibility object allows exact comparison
    without granting it governed authority.
    """

    day_midnight_epoch: int
    state_seconds: np.ndarray
    state_ts_ns: np.ndarray
    bid_ticks: np.ndarray
    ask_ticks: np.ndarray
    valid: np.ndarray

    def __post_init__(self) -> None:
        lengths = {
            len(self.state_seconds),
            len(self.state_ts_ns),
            len(self.bid_ticks),
            len(self.ask_ticks),
            len(self.valid),
        }
        if len(lengths) != 1:
            raise E2AReproductionError("quote state columns differ in length")
        if len(self.state_seconds) and np.any(np.diff(self.state_seconds) <= 0):
            raise E2AReproductionError("quote state seconds are not strictly ordered")

    def quote_at_or_after(self, epoch_second: int, *, maximum_wait: int | None) -> Quote | None:
        local = epoch_second - self.day_midnight_epoch
        if local < 0 or local >= DAY_SECONDS or not len(self.state_seconds):
            return None
        position = int(np.searchsorted(self.state_seconds, local, side="right")) - 1
        if position >= 0 and bool(self.valid[position]):
            found_second = local
            found_position = position
        else:
            start = max(position + 1, 0)
            relative = np.flatnonzero(self.valid[start:])
            if not len(relative):
                return None
            found_position = start + int(relative[0])
            found_second = max(local, int(self.state_seconds[found_position]))
        found_epoch = self.day_midnight_epoch + found_second
        if maximum_wait is not None and found_epoch - epoch_second > maximum_wait:
            return None
        return Quote(
            epoch_second=found_epoch,
            bid_ticks=int(self.bid_ticks[found_position]),
            ask_ticks=int(self.ask_ticks[found_position]),
            source_state_ts_ns=int(self.state_ts_ns[found_position]),
        )

    def last_valid_second(self) -> Quote | None:
        if not len(self.state_seconds):
            return None
        valid_positions = np.flatnonzero(self.valid)
        if not len(valid_positions):
            return None
        position = int(valid_positions[-1])
        if position + 1 < len(self.state_seconds):
            local = int(self.state_seconds[position + 1]) - 1
        else:
            local = DAY_SECONDS - 1
        return Quote(
            epoch_second=self.day_midnight_epoch + local,
            bid_ticks=int(self.bid_ticks[position]),
            ask_ticks=int(self.ask_ticks[position]),
            source_state_ts_ns=int(self.state_ts_ns[position]),
        )


@dataclass(frozen=True, slots=True)
class SignalEvent:
    window_key: str
    event_date: date
    decision_epoch: int
    month_open_date: date
    month_open_ticks: int
    p15_ticks: int
    direction: int

    def as_dict(self) -> dict[str, object]:
        return {
            "decision_epoch": self.decision_epoch,
            "direction": self.direction,
            "event_date": self.event_date.isoformat(),
            "month_open_date": self.month_open_date.isoformat(),
            "month_open_ticks": self.month_open_ticks,
            "p15_ticks": self.p15_ticks,
            "window_key": self.window_key,
        }


@dataclass(frozen=True, slots=True)
class ReplayTrade:
    signal: SignalEvent
    fill_epoch: int
    exit_epoch: int
    entry_px: int
    exit_px: int
    entry_mid_x2: int
    exit_mid_x2: int
    exit_kind: str
    entry_state_age_seconds: str
    exit_state_age_seconds: str

    @property
    def gross_ticks(self) -> int:
        return self.signal.direction * (self.exit_px - self.entry_px)

    @property
    def directed_mid_x2(self) -> int:
        return self.signal.direction * (self.exit_mid_x2 - self.entry_mid_x2)

    def as_dict(self) -> dict[str, object]:
        return {
            **self.signal.as_dict(),
            "directed_mid_ticks": f"{self.directed_mid_x2 / 2:.1f}",
            "entry_mid_ticks": f"{self.entry_mid_x2 / 2:.1f}",
            "entry_px": self.entry_px,
            "entry_state_age_seconds": self.entry_state_age_seconds,
            "exit_epoch": self.exit_epoch,
            "exit_kind": self.exit_kind,
            "exit_mid_ticks": f"{self.exit_mid_x2 / 2:.1f}",
            "exit_px": self.exit_px,
            "exit_state_age_seconds": self.exit_state_age_seconds,
            "fill_epoch": self.fill_epoch,
            "gross_ticks": self.gross_ticks,
        }


def _file_identity(value: os.stat_result) -> tuple[int, int, int, int, int]:
    return (value.st_dev, value.st_ino, value.st_size, value.st_mtime_ns, value.st_ctime_ns)


def _ticks(raw: np.ndarray) -> np.ndarray:
    defined = (raw != UNDEFINED_PRICE) & (raw > 0)
    if np.any(defined & (raw % TICK_PRICE_RAW != 0)):
        raise E2AReproductionError("selected 6E price is positive but off the tick grid")
    return np.where(defined, raw // TICK_PRICE_RAW, -1).astype(np.int64, copy=False)


def _timestamp_ns(column: pa.ChunkedArray | pa.Array) -> np.ndarray:
    return pc.cast(column, pa.int64()).to_numpy(zero_copy_only=False).astype(np.int64, copy=False)


class RawDataset:
    """Verified manifest plus bounded, lazy selected-contract raw readers."""

    def __init__(
        self,
        project_root: Path,
        *,
        verify_source_sha256: bool = True,
        progress: Callable[[str], None] | None = None,
    ) -> None:
        self.project_root = project_root.resolve()
        self.data_root = self.project_root / "data"
        manifest_path = self.project_root / DATASET_MANIFEST_RELATIVE_PATH
        load_bar_dataset_manifest(manifest_path, expected_sha256=DATASET_MANIFEST_SHA256)
        with verified_readonly_file(
            manifest_path,
            expected_sha256=DATASET_MANIFEST_SHA256,
            relative_path=str(DATASET_MANIFEST_RELATIVE_PATH),
        ) as (manifest_handle, _manifest_identity):
            document = json.load(manifest_handle)
        plans: list[DayPlan] = []
        for report in document["reports"]:
            plan = report["plan"]
            if plan["status"] != "SELECTED" or not report["artifacts"]:
                continue
            source_date = date.fromisoformat(plan["source_date"])
            raw_path = (
                self.data_root
                / "mbp-10"
                / source_date.strftime("%Y/%m/%d")
                / (f"glbx-mdp3-{source_date:%Y%m%d}.mbp-10.parquet")
            )
            plans.append(
                DayPlan(
                    source_date=source_date,
                    contract=str(plan["selected_contract"]),
                    instrument_id=int(plan["selected_instrument_id"]),
                    source_sha256=str(plan["source_sha256"]),
                    source_path=raw_path,
                )
            )
        if tuple(item.source_date for item in plans) != tuple(
            sorted(item.source_date for item in plans)
        ):
            raise E2AReproductionError("selected day plans are unordered")
        self.plans = tuple(plans)
        self.by_date = {item.source_date: item for item in plans}
        if len(self.by_date) != len(plans):
            raise E2AReproductionError("selected day plans contain duplicate dates")
        self.verify_source_sha256 = verify_source_sha256
        self.progress = progress
        self._verified: set[date] = set()
        self._verified_identities: dict[date, tuple[int, int, int, int, int]] = {}
        self._trade_cache: OrderedDict[date, TradeTape] = OrderedDict()
        self._quote_cache: OrderedDict[date, LegacyQuoteTape] = OrderedDict()

    @contextmanager
    def verified_parquet(self, plan: DayPlan) -> Iterator[pq.ParquetFile]:
        """Hold and consume the exact inode whose bytes satisfy the manifest SHA."""

        flags = os.O_RDONLY | getattr(os, "O_CLOEXEC", 0) | getattr(os, "O_NOFOLLOW", 0)
        try:
            descriptor = os.open(plan.source_path, flags)
        except OSError as error:
            raise E2AReproductionError(f"cannot open raw source: {plan.source_path}") from error
        handle = os.fdopen(descriptor, "rb", closefd=True)
        try:
            opened = os.fstat(handle.fileno())
            named = os.stat(plan.source_path, follow_symlinks=False)
            identity = _file_identity(opened)
            if (
                not stat.S_ISREG(opened.st_mode)
                or not stat.S_ISREG(named.st_mode)
                or _file_identity(named) != identity
            ):
                raise E2AReproductionError(
                    f"raw source path does not identify the opened regular file: {plan.source_date}"
                )
            if self.progress is not None and plan.source_date not in self._verified:
                self.progress(
                    f"open raw {plan.source_date} {plan.contract}"
                    + (" verify-sha256" if self.verify_source_sha256 else "")
                )
            if (
                self.verify_source_sha256
                and self._verified_identities.get(plan.source_date) != identity
            ):
                digest = hashlib.sha256()
                while chunk := handle.read(8 * 1024 * 1024):
                    digest.update(chunk)
                if digest.hexdigest() != plan.source_sha256:
                    raise E2AReproductionError(f"raw source SHA drifted: {plan.source_date}")
                handle.seek(0)
            self._verified_identities[plan.source_date] = identity
            self._verified.add(plan.source_date)
            parquet = pq.ParquetFile(handle)
            yield parquet
            opened_after = os.fstat(handle.fileno())
            named_after = os.stat(plan.source_path, follow_symlinks=False)
            if _file_identity(opened_after) != identity or _file_identity(named_after) != identity:
                raise E2AReproductionError(
                    f"raw source identity changed while held: {plan.source_date}"
                )
        except (OSError, pa.ArrowException) as error:
            raise E2AReproductionError(
                f"cannot verify raw source while held: {plan.source_date}"
            ) from error
        finally:
            handle.close()

    def _verify(self, plan: DayPlan) -> None:
        """Compatibility verifier; readers should keep :meth:`verified_parquet` held."""

        with self.verified_parquet(plan):
            pass

    @staticmethod
    def _cache_put(cache: OrderedDict[date, object], key: date, value: object) -> None:
        cache[key] = value
        cache.move_to_end(key)
        while len(cache) > 4:
            cache.popitem(last=False)

    def trade_tape(self, source_date: date) -> TradeTape:
        if source_date in self._trade_cache:
            value = self._trade_cache[source_date]
            self._trade_cache.move_to_end(source_date)
            return value
        plan = self.by_date[source_date]
        ts_parts: list[np.ndarray] = []
        price_parts: list[np.ndarray] = []
        with self.verified_parquet(plan) as parquet:
            for row_group in range(parquet.metadata.num_row_groups):
                table = parquet.read_row_group(
                    row_group,
                    columns=["ts_recv", "instrument_id", "action", "price", "flags"],
                    use_threads=False,
                )
                mask = pc.and_(
                    pc.equal(table["instrument_id"], pa.scalar(plan.instrument_id, pa.uint32())),
                    pc.equal(table["action"], pa.scalar("T")),
                )
                selected = table.filter(mask)
                if not selected.num_rows:
                    continue
                flags = selected["flags"].to_numpy(zero_copy_only=False)
                keep = (flags & F_BAD_TS_RECV) == 0
                if not np.any(keep):
                    continue
                raw_price = selected["price"].to_numpy(zero_copy_only=False).astype(np.int64)[keep]
                price = _ticks(raw_price)
                valid_price = price > 0
                ts_parts.append(_timestamp_ns(selected["ts_recv"])[keep][valid_price])
                price_parts.append(price[valid_price])
        if not ts_parts:
            raise E2AReproductionError(f"selected contract has no clean trades: {source_date}")
        ts = np.concatenate(ts_parts)
        prices = np.concatenate(price_parts)
        if np.any(np.diff(ts) < 0):
            raise E2AReproductionError(f"selected trade timestamps regressed: {source_date}")
        seconds = ts // SECOND_NS
        last = np.r_[np.flatnonzero(seconds[:-1] != seconds[1:]), len(seconds) - 1]
        tape = TradeTape(ts, prices, seconds[last], prices[last])
        self._cache_put(self._trade_cache, source_date, tape)
        return tape

    def legacy_quote_tape(self, source_date: date) -> LegacyQuoteTape:
        if source_date in self._quote_cache:
            value = self._quote_cache[source_date]
            self._quote_cache.move_to_end(source_date)
            return value
        plan = self.by_date[source_date]
        ts_parts: list[np.ndarray] = []
        bid_parts: list[np.ndarray] = []
        ask_parts: list[np.ndarray] = []
        with self.verified_parquet(plan) as parquet:
            for row_group in range(parquet.metadata.num_row_groups):
                table = parquet.read_row_group(
                    row_group,
                    columns=[
                        "ts_recv",
                        "instrument_id",
                        "flags",
                        "bid_px_00",
                        "ask_px_00",
                    ],
                    use_threads=False,
                )
                selected = table.filter(
                    pc.equal(table["instrument_id"], pa.scalar(plan.instrument_id, pa.uint32()))
                )
                if not selected.num_rows:
                    continue
                flags = selected["flags"].to_numpy(zero_copy_only=False)
                keep = (flags & LEGACY_BAD_FLAG_MASK) == 0
                if not np.any(keep):
                    continue
                ts_parts.append(_timestamp_ns(selected["ts_recv"])[keep])
                bid_parts.append(
                    selected["bid_px_00"].to_numpy(zero_copy_only=False).astype(np.int64)[keep]
                )
                ask_parts.append(
                    selected["ask_px_00"].to_numpy(zero_copy_only=False).astype(np.int64)[keep]
                )
        if not ts_parts:
            raise E2AReproductionError(f"selected contract has no quote states: {source_date}")
        ts = np.concatenate(ts_parts)
        raw_bid = np.concatenate(bid_parts)
        raw_ask = np.concatenate(ask_parts)
        if np.any(np.diff(ts) < 0):
            raise E2AReproductionError(f"selected quote timestamps regressed: {source_date}")
        seconds = ts // SECOND_NS - plan.midnight_epoch
        in_day = (seconds >= 0) & (seconds < DAY_SECONDS)
        ts, raw_bid, raw_ask, seconds = (
            ts[in_day],
            raw_bid[in_day],
            raw_ask[in_day],
            seconds[in_day],
        )
        if not len(seconds):
            raise E2AReproductionError(
                f"selected quote states fall outside source date: {source_date}"
            )
        last = np.r_[np.flatnonzero(seconds[:-1] != seconds[1:]), len(seconds) - 1]
        ts, raw_bid, raw_ask, seconds = ts[last], raw_bid[last], raw_ask[last], seconds[last]
        bid = _ticks(raw_bid)
        ask = _ticks(raw_ask)
        valid = (bid > 0) & (ask > 0) & (ask >= bid)
        tape = LegacyQuoteTape(plan.midnight_epoch, seconds, ts, bid, ask, valid)
        self._cache_put(self._quote_cache, source_date, tape)
        return tape


def london_decision_epoch(event_date: date, config: E2AConfig) -> int:
    return int(
        datetime(
            event_date.year,
            event_date.month,
            event_date.day,
            config.decision_hour,
            config.decision_minute,
            tzinfo=LONDON,
        ).timestamp()
    )


@dataclass(frozen=True, slots=True)
class VerifiedFileIdentity:
    """Identity of bytes read from one held, manifest-matched regular file."""

    byte_size: int
    relative_path: str
    sha256: str

    def as_dict(self) -> dict[str, object]:
        return {
            "byte_size": self.byte_size,
            "relative_path": self.relative_path,
            "sha256": self.sha256,
        }


@contextmanager
def verified_readonly_file(
    path: Path,
    *,
    expected_sha256: str,
    relative_path: str,
) -> Iterator[tuple[BinaryIO, VerifiedFileIdentity]]:
    """Hash and consume the same held inode, rejecting path or byte drift."""

    if len(expected_sha256) != 64 or any(
        character not in "0123456789abcdef" for character in expected_sha256
    ):
        raise E2AReproductionError(f"expected SHA-256 is invalid: {relative_path}")
    flags = os.O_RDONLY | getattr(os, "O_CLOEXEC", 0) | getattr(os, "O_NOFOLLOW", 0)
    try:
        descriptor = os.open(path, flags)
    except OSError as error:
        raise E2AReproductionError(f"cannot open verified file: {relative_path}") from error
    handle = os.fdopen(descriptor, "rb", closefd=True)
    try:
        opened = os.fstat(handle.fileno())
        named = os.stat(path, follow_symlinks=False)
        identity = _file_identity(opened)
        if (
            not stat.S_ISREG(opened.st_mode)
            or not stat.S_ISREG(named.st_mode)
            or _file_identity(named) != identity
        ):
            raise E2AReproductionError(
                f"verified path does not identify the opened regular file: {relative_path}"
            )
        digest = hashlib.sha256()
        while chunk := handle.read(8 * 1024 * 1024):
            digest.update(chunk)
        actual_sha256 = digest.hexdigest()
        if actual_sha256 != expected_sha256:
            raise E2AReproductionError(f"verified file SHA drifted: {relative_path}")
        handle.seek(0)
        verified = VerifiedFileIdentity(
            byte_size=opened.st_size,
            relative_path=relative_path,
            sha256=actual_sha256,
        )
        try:
            yield handle, verified
        finally:
            opened_after = os.fstat(handle.fileno())
            named_after = os.stat(path, follow_symlinks=False)
            if _file_identity(opened_after) != identity or _file_identity(named_after) != identity:
                raise E2AReproductionError(f"verified file changed while held: {relative_path}")
    except OSError as error:
        raise E2AReproductionError(f"cannot verify held file: {relative_path}") from error
    finally:
        handle.close()


def calendar_event_date(active_dates: tuple[date, ...], year: int, month: int) -> date | None:
    eligible = [
        item
        for item in active_dates
        if item.year == year and item.month == month and item.weekday() < 5
    ]
    return max(eligible) if eligible else None


def legacy_adjacency_event_dates(active_dates: tuple[date, ...]) -> tuple[date, ...]:
    return tuple(
        current
        for current, following in pairwise(active_dates)
        if current.month != following.month and current.weekday() < 5
    )


def _months_between(start: date, end: date) -> tuple[tuple[int, int], ...]:
    values: list[tuple[int, int]] = []
    year, month = start.year, start.month
    while (year, month) <= (end.year, end.month):
        values.append((year, month))
        month += 1
        if month == 13:
            year += 1
            month = 1
    return tuple(values)


def derive_signals(
    dataset: RawDataset,
    config: E2AConfig,
    *,
    calendar_mode: CalendarMode = "CALENDAR_LAST_ELIGIBLE_WEEKDAY",
) -> tuple[SignalEvent, ...]:
    """Rebuild every frozen-window signal from raw selected-contract trades."""

    active_dates = tuple(item.source_date for item in dataset.plans)
    adjacency = set(legacy_adjacency_event_dates(active_dates))
    events: list[SignalEvent] = []
    for window in config.historical_windows:
        for year, month in _months_between(window.decision_start, window.decision_end):
            event_date = calendar_event_date(active_dates, year, month)
            if event_date is None or not (
                window.decision_start <= event_date <= window.decision_end
            ):
                continue
            if calendar_mode == "LEGACY_METAS_ADJACENCY" and event_date not in adjacency:
                continue
            month_dates = [
                item for item in active_dates if item.year == year and item.month == month
            ]
            if not month_dates:
                continue
            month_open_date = min(month_dates)
            opening_tape = dataset.trade_tape(month_open_date)
            if not len(opening_tape.bar_start_seconds):
                continue
            opening_lookup = (
                int(opening_tape.bar_start_seconds[0]) + config.month_open_lookup_seconds
            )
            month_open = opening_tape.legacy_bar_close(
                opening_lookup,
                maximum_staleness=config.month_open_staleness_seconds,
            )
            decision_epoch = london_decision_epoch(event_date, config)
            p15 = dataset.trade_tape(event_date).physical_trade_at_or_before(
                decision_epoch * SECOND_NS,
                maximum_staleness_seconds=config.p15_staleness_seconds,
            )
            if month_open is None or p15 is None or p15 == month_open:
                continue
            events.append(
                SignalEvent(
                    window_key=window.key,
                    event_date=event_date,
                    decision_epoch=decision_epoch,
                    month_open_date=month_open_date,
                    month_open_ticks=month_open,
                    p15_ticks=p15,
                    direction=-1 if p15 > month_open else 1,
                )
            )
    return tuple(events)


def _plan_index(dataset: RawDataset, source_date: date) -> int:
    dates = np.array([item.source_date.toordinal() for item in dataset.plans], dtype=np.int64)
    position = int(np.searchsorted(dates, source_date.toordinal(), side="left"))
    if position >= len(dates) or int(dates[position]) != source_date.toordinal():
        raise E2AReproductionError(f"source date is not active: {source_date}")
    return position


def _legacy_quote_across_days(
    dataset: RawDataset,
    epoch_second: int,
    *,
    maximum_wait: int | None,
    last_plan_index: int | None = None,
) -> Quote | None:
    date_ordinals = np.array(
        [item.source_date.toordinal() for item in dataset.plans], dtype=np.int64
    )
    requested_date = datetime.fromtimestamp(epoch_second, UTC).date().toordinal()
    position = int(np.searchsorted(date_ordinals, requested_date, side="right")) - 1
    position = max(position, 0)
    if epoch_second >= dataset.plans[position].midnight_epoch + DAY_SECONDS:
        position += 1
    limit = len(dataset.plans) - 1 if last_plan_index is None else last_plan_index
    while position <= limit:
        plan = dataset.plans[position]
        local_start = max(epoch_second, plan.midnight_epoch)
        quote = dataset.legacy_quote_tape(plan.source_date).quote_at_or_after(
            local_start,
            maximum_wait=None,
        )
        if quote is not None:
            if maximum_wait is not None and quote.epoch_second - epoch_second > maximum_wait:
                return None
            return quote
        position += 1
    return None


def _legacy_boundary_after(dataset: RawDataset, fill_epoch: int) -> tuple[Quote, int]:
    source_date = datetime.fromtimestamp(fill_epoch, UTC).date()
    position = _plan_index(dataset, source_date)
    for index in range(position, len(dataset.plans)):
        plan = dataset.plans[index]
        following = dataset.plans[index + 1] if index + 1 < len(dataset.plans) else None
        force = following is None or following.contract != plan.contract
        if following is not None:
            gap = following.midnight_epoch - plan.midnight_epoch
            force = force or gap > 96 * 3_600
        if force:
            quote = dataset.legacy_quote_tape(plan.source_date).last_valid_second()
            if quote is None:
                continue
            if quote.epoch_second <= fill_epoch:
                raise E2AReproductionError("force-exit boundary is not after the fill")
            return quote, index
    raise E2AReproductionError("no force-exit boundary exists")


def replay_legacy_lab_grid(
    dataset: RawDataset,
    config: E2AConfig,
    signals: tuple[SignalEvent, ...],
) -> tuple[ReplayTrade, ...]:
    """Replay the disclosed signals under the lab-compatible quote semantics."""

    output: list[ReplayTrade] = []
    busy_until = -1
    for signal in sorted(signals, key=lambda item: item.decision_epoch):
        if signal.decision_epoch <= busy_until:
            continue
        entry = _legacy_quote_across_days(
            dataset,
            signal.decision_epoch + config.entry_delay_seconds,
            maximum_wait=config.entry_wait_seconds,
        )
        if entry is None:
            continue
        target = entry.epoch_second + config.holding_seconds
        boundary, boundary_index = _legacy_boundary_after(dataset, entry.epoch_second)
        if target >= boundary.epoch_second:
            exit_quote = boundary
            exit_kind = "BOUNDARY"
        else:
            exit_quote = _legacy_quote_across_days(
                dataset,
                target,
                maximum_wait=None,
                last_plan_index=boundary_index,
            )
            exit_kind = "HORIZON"
        if exit_quote is None:
            continue
        direction = signal.direction
        entry_px = entry.ask_ticks if direction == 1 else entry.bid_ticks
        exit_px = exit_quote.bid_ticks if direction == 1 else exit_quote.ask_ticks
        output.append(
            ReplayTrade(
                signal=signal,
                fill_epoch=entry.epoch_second,
                exit_epoch=exit_quote.epoch_second,
                entry_px=entry_px,
                exit_px=exit_px,
                entry_mid_x2=entry.bid_ticks + entry.ask_ticks,
                exit_mid_x2=exit_quote.bid_ticks + exit_quote.ask_ticks,
                exit_kind=exit_kind,
                entry_state_age_seconds=f"{(entry.epoch_second * SECOND_NS - entry.source_state_ts_ns) / SECOND_NS:.9f}",
                exit_state_age_seconds=f"{(exit_quote.epoch_second * SECOND_NS - exit_quote.source_state_ts_ns) / SECOND_NS:.9f}",
            )
        )
        busy_until = exit_quote.epoch_second
    return tuple(output)


def window_summary(
    trades: tuple[ReplayTrade, ...], *, debit_ticks_x2: int = 3
) -> dict[str, object]:
    gross = sum(item.gross_ticks for item in trades)
    net_x2 = 2 * gross - debit_ticks_x2 * len(trades)
    wins = sum(2 * item.gross_ticks - debit_ticks_x2 > 0 for item in trades)
    return {
        "event_count": len(trades),
        "gross_ticks": gross,
        "net_ticks": f"{net_x2 / 2:.1f}",
        "wins": wins,
    }


def provisional_forward_dates(config: E2AConfig) -> tuple[date, ...]:
    """Outcome-blind weekday opportunities; eligibility remains unknown in advance."""

    candidates: list[date] = []
    for year, month in _months_between(
        config.forward_opportunity_start,
        config.forward_opportunity_end,
    ):
        if month == 12:
            next_month = date(year + 1, 1, 1)
        else:
            next_month = date(year, month + 1, 1)
        value = next_month - timedelta(days=1)
        while value.weekday() >= 5:
            value -= timedelta(days=1)
        candidates.append(value)
    return tuple(candidates)
